Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'


urlpatterns = [    
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('comment/<int:pizza_id>/',views.comment, name='comment'),
    ] 
    

pizzas/models.py
from email.mime import image
from django.db import models

from Pizzeria.settings import MEDIA_URL

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='img',blank=True,null=True)
    

    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField()

    def __str__(self):
        return f"{self.topping_name[:50]}..."

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment_text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.comment_text[:50]}..."

pizzas/forms.py
from tkinter import Widget
from django import forms

from .models import Comment, Pizza,Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['pizza_name']
        labels = {'pizza_name':''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['topping_name']
        labels = {'topping_name':''}
        widgets = {'topping_name': forms.Textarea(attrs={'cols':80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']
        labels = {'comment_text':''}
        widgets = {'comment_text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from email.mime import image
from django.shortcuts import render, redirect

from .forms import PizzaForm,ToppingForm,CommentForm
from .models import Pizza, Topping


# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')



def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas}

    return render(request,'pizzas/pizzas.html',context)


def pizza(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    comments = pizza.comment_set.order_by('-date_added')
    image = Pizza.image

    context = {'pizza':pizza,'toppings':toppings,'comments':comments,'image':image}

    return render(request, 'pizzas/pizza.html', context)



def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            return redirect('pizzas:pizza',pizza_id=pizza_id)
    
    context = {'form':form,'pizza':pizza}
    return render(request, 'pizzas/comment.html',context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no">
    <title>Philip's Pizzeria</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index'%}">
            Philip's Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzas:pizzas'%}">
                        Pizzas</a>
                </li>
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>
</body>

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}


{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }} </a></p>

<p>Add a comment:</p>

<form action="{% url 'pizzas:comment' pizza.id %}" method='post'>

    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Add comment</button>


</form>

<style>
    body {

        background-image: url(https://c8.alamy.com/comp/RKY7FC/half-of-delicious-classic-italian-pizza-with-spicy-chicken-mushrooms-and-cheese-isolated-on-white-background-RKY7FC.jpg);
    }
</style>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Welcome to Philip's Pizzeria!</h1>
    <p class="lead">We are ready to serve you the best pizza you have ever had!!!</p>
</div>

<style>
    body {

        background-image: url(https://i.pinimg.com/originals/ba/19/b8/ba19b8e7f80036b04579dd7447d815a6.jpg);
    }
</style>

{% endblock page_header %}

pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %}


{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }} </a></p>

<p>Add a new topping:</p>

<form action="{% url 'pizzas:new_topping' pizza.id %}" method='post'>

    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Add Topping</button>


</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block page_header %}
<h3>{{ pizza }}</h3>
{% endblock page_header %}

{% block content %}
<p>
    <img src="{{ pizza.image.url }}">
</p>
<ul>
    {% for t in toppings %}
    <div class="card mb-3">
        <h4 class="card-header">
            {{ t.topping_name }}
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>
    {% empty %}
    <p> There are no toppings for this pizza yet. </p>
    {% endfor %}
</ul>

<p><a href="{% url 'pizzas:comment' pizza.id %}">Add comment</a></p>

<ul>
    {% for c in comments %}
    <div class="card mb-3"></div>
    <h4 class="card-header">
        {{ c.date_added|date:'M d, Y H:i' }}
    </h4>
    <div class="card-body">
        {{ c.comment_text|linebreaks }}
    </div>
    </div>
    {% empty %}
    <p>There are no comments for this pizza. Please feel free to add one! </p>
    {% endfor %}
</ul>


{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block page_header %}
<h1>Our Pizzas</h1>
{% endblock page_header %}

{% block content %}

<ul>
    {% for p in pizzas %}

    <li>
        <h3>
            <a href="{%url 'pizzas:pizza' p.id %}">{{ p }} </a>
        </h3>
    </li>
    {% empty %}
    <li>
        <h3>No pizzas have been added yet.
    </li>
    </h3>
    {% endfor %}
</ul>

<style>
    body {

        background-image: url(http://lofrev.net/wp-content/photos/2014/10/Pizza-3D-logo.jpg);
    }
</style>

{% endblock content %}